### ISSUE TITLE
Use logging library in spidermon

### ISSUE THREAD

**Issue by rennerocha** [scrapinghub/spidermon#102]
Some actions uses `print` for logging:
- https://github.com/scrapinghub/spidermon/blob/master/spidermon/contrib/actions/email/__init__.py#L77
- https://github.com/scrapinghub/spidermon/blob/master/spidermon/contrib/actions/slack/__init__.py#L179

Python built-in [logging](https://docs.python.org/3.5/library/logging.html) library should be used instead (like 
[here](https://github.com/scrapinghub/spidermon/blob/master/spidermon/contrib/actions/sentry/__init__.py#L3)).

**Comment by leovictorsr** [comment]
@ejulio hello Julio, we spoke via email, I'll work on this issue as my first for Spidermon.

**Comment by ejulio** [comment]
hey @leovictorsr.
That's awesome to hear!
If you need anything, just ping me I'll try to help you :smile:
