### ISSUE TITLE
Create a Release Notes for version 1.9

### ISSUE THREAD

**Issue by raphapassini** [scrapinghub/spidermon#104]
Create a release notes, for this we need to keep track about what was merged into master, suggestions here?

**Comment by ejulio** [comment]
About release notes, I like the idea of using git logs.
But, not sure if it would be feasible..

**Comment by manycoding** [comment]
I normally read merge logs. For that, I have to put only the necessary information there.
@alexander-matsievsky has a good experience with automating changelogs extraction

**Comment by rennerocha** [comment]
Probably we will need a better process for the next release.
For this release I created a changelog based on the issues/PRs that exists in the milestone 1.9.0
https://github.com/scrapinghub/spidermon/pull/105

**Comment by ejulio** [comment]
I would go with @manycoding idea in the future.
We can automate it and makes it easier to maintain in the future.

**Comment by manycoding** [comment]
@ejulio I meant that I do it manually in one project, to achieve that I keep my log as clean and informative as possible.
But I know that @alexander-matsievsky automated this, so that's another way.

**Comment by kmike** [comment]
hey! my2c: I think it'd be unreasonable to ask third-party contributions to use detailed conventions like https://www.conventionalcommits.org/en/v1.0.0-beta.3/ for commit names :) 
@ivanprado share a nice link recently - https://keepachangelog.com/en/1.0.0/

**Comment by alexander-matsievsky** [comment]
@kmike Actually that's not a problem, Mikhail.

> **Do all my contributors need to use the conventional commit specification?**
> 
> No! If you use a squash based workflow on Git lead maintainers can cleanup the commit messages as they’re merged—adding no workload to casual committers. A common workflow for this is to have your git system automatically squash commits from a pull request and present a form for the lead maintainer to enter the proper git commit message for the merge.
> 
> — <cite>https://www.conventionalcommits.org/en/v1.0.0-beta.3/#do-all-my-contributors-need-to-use-the-conventional-commit-specification<cite>

**Comment by alexander-matsievsky** [comment]
@kmike Regarding https://keepachangelog.com/en/1.0.0/ the output of CC https://github.com/yargs/yargs/blob/master/CHANGELOG.md respects all the Guiding Principles.

**Comment by raphapassini** [comment]
@rennerocha is working to both implement this and update the contribute guide.
