### ISSUE TITLE
Follow python end of life https://devguide.python.org/

### ISSUE THREAD

**Issue by manycoding** [scrapinghub/spidermon#107]
I propose to follow [Python dev guidelines](https://devguide.python.org/). I thought it was idea from the start that we actually won't support Python2 officialy in this library.

  _Here you can think of all benefits which you can get by removing Python2 support altogether_

But in the end it's all the same - guidelines there are for certain reasons, and something old eventually will stop working of will block this library development, sooner or later.

So I propose to actually:
1. deprecate python2
2. python 3.4.

Alive projects where Python2 support is needed can use an archived version or switch to 3.

**Comment by raphapassini** [comment]
+1 to see this one in the next release.

**Comment by Gallaecio** [comment]
I think we should try to support Python versions until their end of life. Which means that the next version can drop support for 3.4 (end of life reached on 2019-03-19), but that we should try and support 2.7 until 2020-01-01.

**Comment by manycoding** [comment]
@Gallaecio And the reasons for that?
Support means we ensure that it works on particular versions

I see only the downsides - providing a good excuse to continue to use outdated tools for users.

**Comment by vipulgupta2048** [comment]
I am also in favor of porting and follow the Python guidelines to not support Python2 in the next release. The experience that I have from my time at Sugar Labs in regards to porting and migration to Python3 is quite rocky. The process takes time, planning, and a lot of little fixes to be done both in code and documentation, I am not exactly sure of how much code/packages of Spidermon are in Python2.7 but we should really start planning/working towards it.

Since Python2.7 support ends on 2020-01-01 maybe we can work towards support it till August or September maybe. And work on the porting in the background till then. Even the latest software releases comes with Python3 support.

**Comment by Gallaecio** [comment]
Where in https://devguide.python.org/ does it recommend not to support Python 2?

**Comment by manycoding** [comment]
@Gallaecio I think there are plenty of information about that, like here https://wiki.python.org/moin/Python2orPython3

**Comment by manycoding** [comment]
@Gallaecio I found a good one https://python3statement.org/

**Comment by Gallaecio** [comment]
> @Gallaecio I think there are plenty of information about that, like here https://wiki.python.org/moin/Python2orPython3

They only recommend Python 3 when you have to choose between Python 2 and Python 3. That is, they recommend Python 3 for new non-library projects. Which makes perfect sense, but I don’t think that applies to Spidermon, as a library to be used from existing projects, some of which may still use Python 2.

In fact, the article has [a section on how to support both versions](https://wiki.python.org/moin/Python2orPython3#Supporting_Python_2_and_Python_3_in_a_common_code_base).

> @Gallaecio I found a good one https://python3statement.org/
> What are the concerns in particular?

From there:

> The developers of the Python language extended support of Python 2.7 from 2015 to January 1, 2020, recognising that many people were still using Python 2. We believe that the extra 5 years is sufficient to transition off of Python 2, and our projects plan to stop supporting Python 2 when upstream support ends in 2020, if not before. We will then be able to simplify our code and take advantage of the many new features in the current version of the Python language and standard library.

I think this is what I am suggesting. Keeping the existing Python 2 support we have for the following 9 months, until Python 2 reaches end of life.

The paragraph after that states:

> In addition, significantly before 2020, many of our projects will step down Python 2.7 support to only fixing bugs, and require Python 3 for all new feature releases. Some projects have already made this transition. This too parallels support for the language itself, as Python 2.7 releases only include bugfixes and security improvements.

I think this proposal, maintaining a second branch which supports Python 2 and receives bugfixes, with its own releases, could be more time consuming for us.

**Comment by rennerocha** [comment]
I agree with @Gallaecio . We still have a large code base using Python 2.7 that would be benefited with new features introduced in Spidermon. Given the open issues we have, I don't see any feature in the next 9 months that will be punished if we code it maintaining Python 2.7 support.

I am ok of dropping Python 3.4 support in the next release as it already reached its end-of-life.

**Comment by manycoding** [comment]
Ok, so we all agree upon following official end of life and drop support? Unless somebody pays us.

**Comment by vipulgupta2048** [comment]
Hey folks, reading and raising this topic again.
I think we can at least start with the migration work and work towards the goal of dropping support for python 27 and python < 3.4
What say? Should we get the ball rolling now or after the end of life of Python2.7

**Comment by rennerocha** [comment]
As the project is build to help Scrapy users, we should try to support the versions that are supported by it. At this moment, we will support Python 3.5+. Support for older versions was dropped.
