### ISSUE TITLE
Create a base monitor to compare with previous crawls

### ISSUE THREAD

**Issue by ejulio** [scrapinghub/spidermon#122]
Often, we compare the current crawling result with a previous one.
The idea here is to create some kind of base monitor that would make it a bit easier.
Basically, we need:
* Some sort of storage provider (we can use `python-scrapinghub` by default, but we need to make extensible for any kind of storage)
* A base monitor that would load last crawl data, an entry point to compare with the current one, storage the current crawl data.

Anything else you think is worth adding here?

**Comment by ejulio** [comment]
I'll put some effort to move this issue :)
Here is what @rennerocha , @raphapassini and I discussed about the desired behavior to be added.

We'll provide two storage backends by default:

* `python-scrapinghub` to use past jobs stats in scrapy cloud.
* `local storae` to save the data to a /temp folder locally and then the user can persist it to wherever he wants
* In future version we can add support for AWS, GCS, and others

The backends will follow a basic interface with a method to load the past jobs stats and to store the current one.

We'll add a new setting so that the user can configure how many past jobs to keep.
`SPIDERMON_SOMETHING = 10`
Then, when running a monitor to compare with past jobs, it'll receive a list with stats from the last 10 jobs. Note that there might be limitations depending on the backend.

For monitoring, we'll add a new base monitor that will call the test methods with historical stats.
The idea is something like
```
class MyHistoricalMonitor(spidermon.HistoricalMonitor): # must work on the names :b
    @monitor('not far from the historical mean')
    def test_number_of_items_similar_to_historical_mean(self, past_stats):
        mean = compute_mean(past_stats) # past_stats is a list of stats dicts from past jobs
        std = compute_std(past_stats)
        assert mean - std <= crawled_items <= mean + std
```

**Comment by rennerocha** [comment]
This was done in https://github.com/scrapinghub/spidermon/pull/137 
Now you can enable a custom StatsCollector that will store the previous stats from your spider execution, allowing you to compare it in your own monitor.
