### ISSUE TITLE
What is the difference between render_text_template and render_template?

### ISSUE THREAD

**Issue by matiskay** [scrapinghub/spidermon#124]
Hi,

I would like to know what is the intention of `render_text_template` and `render_template` methods in `/contrib/actions/templates.py`. 

https://github.com/scrapinghub/spidermon/blob/47b052b86b2ad1197f87eb37f4ce21a7c2e7516b/spidermon/contrib/actions/templates.py#L37-L43

both are the same.

**Comment by raphapassini** [comment]
@matiskay this could be better documented. It's used to set the `MimeType` of the content in the email

```python
        message.attach(MIMEText(body_text, "plain"))
        if body_html:
            message.attach(MIMEText(body_html, "html"))

        return message
```
