### ISSUE TITLE
Add default template to email actions

### ISSUE THREAD

**Issue by matiskay** [scrapinghub/spidermon#125]
It would be great to use `reports/email/monitors/result.jinja` as the default template for `SPIDERMON_BODY_HTML_TEMPLATE`.

**Comment by vipulgupta2048** [comment]
I would like to take this up. I think this could be the right place to have this in the file https://github.com/scrapinghub/spidermon/blob/bf51f3381ac01dc7b85032f34c3686a94a5c9b46/spidermon/contrib/actions/email/__init__.py#L84 

`"body_text_template": crawler.settings.get("SPIDERMON_BODY_TEXT_TEMPLATE") or `Path/to/result.jinja` ,

In reference to:
https://github.com/scrapinghub/spidermon/blob/master/spidermon/contrib/actions/reports/templates/reports/email/monitors/result.jinja

CC: @matiskay @rennerocha

**Comment by rosheen33** [comment]
#https://github.com/scrapinghub/spidermon/pull/171

**Comment by rosheen33** [comment]
PR is merged

**Comment by rosheen33** [comment]
@rennerocha @raphapassini PR is merged I am going to close this issue.
