### ISSUE TITLE
How to set a local/custom template in Email actions

### ISSUE THREAD

**Issue by matiskay** [scrapinghub/spidermon#126]
Hi,

I would like to know if there is way to pass  a local jinja template to the actions. I'm setting a local path and absolute path in `SPIDERMON_BODY_HTML_TEMPLATE`  but  I'm getting a `TemplateNotFound` error.

I tried `SPIDERMON_BODY_HTML_TEMPLATE = 'reports/email/monitors/result.jinja'` and it worked but I would like to add my own template.

It looks like jinja2 loader only looks at `/spidermon/contrib/actions/reports/templates/` folder inside `spidermon` package.

**Comment by rennerocha** [comment]
Try creating a custom action and include the path for your template inside `template_paths` [class attribute](https://github.com/scrapinghub/spidermon/blob/master/spidermon/contrib/actions/templates.py#L27). This should solve your problem for now, but I believe it would be a good idea to add a new setting to allow us to define a list of locations that we want the templates to be searched against.

**Comment by rennerocha** [comment]
When trying to [load a template](https://github.com/scrapinghub/spidermon/blob/master/spidermon/templates.py#L74) that is an absolute path, Jinja2 loader didn't look at the right place, but instead it concatenates the provided absolute path to the paths loaded in the `Environment`.

At this moment you can not use absolute paths for Spidermon's custom templates. You need to create a custom action inherited from `[ActionWithTemplates](https://github.com/scrapinghub/spidermon/blob/master/spidermon/contrib/actions/templates.py#L26)` and define the `[template_paths](https://github.com/scrapinghub/spidermon/blob/master/spidermon/contrib/actions/templates.py#L27) containing the absolute location of your desired template.

**Comment by rennerocha** [comment]
Considering that my template is located in `/absolute/location/of/my/template/template_name.jinja`

```
from spidermon.contrib.actions.email import SendEmail

class MyCustomSendEmail(SendEmail):
  template_paths = ["/absolute/location/of/my/template"]
```

and add to `settings.py`:

```
SPIDERMON_BODY_HTML_TEMPLATE = "template_name.jinja"
````

**Comment by rennerocha** [comment]
@matiskay Spidermon 1.10.2 allows you to set an absolute path for your custom templates.
If you find any problems, refer to this issue again.
