### ISSUE TITLE
`schematics` required but not installed by default

### ISSUE THREAD

**Issue by andrewbaxter** [scrapinghub/spidermon#140]
I installed with `pip install spidermon`, got 1.9.0.

So I rechecked the installation docs just in case, but trying to use jsonschema validation I get:

```
2019-04-05 19:51:42 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/andrew/scraping/temp/30/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/andrew/scraping/temp/30/env/lib/python3.6/site-packages/scrapy/crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "/home/andrew/scraping/temp/30/env/lib/python3.6/site-packages/scrapy/crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/home/andrew/scraping/temp/30/env/lib/python3.6/site-packages/scrapy/core/engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "/home/andrew/scraping/temp/30/env/lib/python3.6/site-packages/scrapy/core/scraper.py", line 71, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/home/andrew/scraping/temp/30/env/lib/python3.6/site-packages/scrapy/middleware.py", line 53, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/home/andrew/scraping/temp/30/env/lib/python3.6/site-packages/scrapy/middleware.py", line 34, in from_settings
    mwcls = load_object(clspath)
  File "/home/andrew/scraping/temp/30/env/lib/python3.6/site-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/andrew/scraping/temp/30/env/lib/python3.6/site-packages/spidermon/contrib/scrapy/pipelines.py", line 13, in <module>
    from spidermon.contrib.validation import SchematicsValidator, JSONSchemaValidator
  File "/home/andrew/scraping/temp/30/env/lib/python3.6/site-packages/spidermon/contrib/validation/__init__.py", line 1, in <module>
    from .schematics.validator import SchematicsValidator
  File "/home/andrew/scraping/temp/30/env/lib/python3.6/site-packages/spidermon/contrib/validation/schematics/validator.py", line 4, in <module>
    import schematics
ModuleNotFoundError: No module named 'schematics'
```

Installing `schematics` fixed the issue.

It's possible I have my project misconfigured (#139).  My settings look like this:
```
SPIDERMON_ENABLED = True
EXTENSIONS = {
    'spidermon.contrib.scrapy.extensions.Spidermon': 500,
}
ITEM_PIPELINES = {
    'spidermon.contrib.scrapy.pipelines.ItemValidationPipeline': 800,
}
SPIDERMON_VALIDATION_ADD_ERRORS_TO_ITEMS = True
SPIDERMON_VALIDATION_SCHEMAS = [
    'schema.json',
]
```

**Comment by vipulgupta2048** [comment]
Thanks, @andrewbaxter, for bringing the issue to light. 
I am trying to debug your issue by reproducing the same. Followed the following steps. 
- Created scrapy new project and schema.json. Added reference to schema.json in the settings.
- Made a venv on top of it, installed Spidermon with no errors. Log below.  
```
~/x $ pip install --no-cache-dir spidermon
Collecting spidermon
  Downloading https://files.pythonhosted.org/packages/66/13/6d60d6941c55866f1f7ee9ded55c0c3c825592e9fe561825ec8f500883b1/spidermon-1.9.0-py2.py3-none-any.whl (92kB)
    100% |████████████████████████████████| 92kB 825kB/s 
Collecting jsonschema (from spidermon)
  Downloading https://files.pythonhosted.org/packages/aa/69/df679dfbdd051568b53c38ec8152a3ab6bc533434fc7ed11ab034bf5e82f/jsonschema-3.0.1-py2.py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 5.6MB/s 
Collecting python-slugify (from spidermon)
  Downloading https://files.pythonhosted.org/packages/c1/19/c3cf1dc65e89aa999f85a4a3a4924ccac765a6964b405d487b7b7c8bb39f/python-slugify-3.0.2.tar.gz
Collecting six>=1.9.0 (from spidermon)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting pyrsistent>=0.14.0 (from jsonschema->spidermon)
  Downloading https://files.pythonhosted.org/packages/8c/46/4e93ab8a379d7efe93f20a0fb8a27bdfe88942cc954ab0210c3164e783e0/pyrsistent-0.14.11.tar.gz (104kB)
    100% |████████████████████████████████| 112kB 1.9MB/s 
Requirement already satisfied: setuptools in /home/vipulgupta2048/.virtualenvs/bro/lib/python3.6/site-packages (from jsonschema->spidermon) (41.0.0)
Collecting attrs>=17.4.0 (from jsonschema->spidermon)
  Downloading https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting text-unidecode==1.2 (from python-slugify->spidermon)
  Downloading https://files.pythonhosted.org/packages/79/42/d717cc2b4520fb09e45b344b1b0b4e81aa672001dd128c180fabc655c341/text_unidecode-1.2-py2.py3-none-any.whl (77kB)
    100% |████████████████████████████████| 81kB 2.5MB/s 
Installing collected packages: six, pyrsistent, attrs, jsonschema, text-unidecode, python-slugify, spidermon
  Running setup.py install for pyrsistent ... done
  Running setup.py install for python-slugify ... done
Successfully installed attrs-19.1.0 jsonschema-3.0.1 pyrsistent-0.14.11 python-slugify-3.0.2 six-1.12.0 spidermon-1.9.0 text-unidecode-1.2
```
Am I doing right? Any other steps that you took?

**Comment by andrewbaxter** [comment]
The output you posted is expected I think - the issue is that `schematics` is not installed but Spidermon imports it or otherwise relies on it.

**Comment by vipulgupta2048** [comment]
Ahh ... I see the point you are making. On close observation, `schematics` is not getting installed with `pip install spidermon` 

**Steps that I followed**
- Made a new directory, new venv, did a `pip install spidermon`
- Output of `pip freeze` is as follows 

```
~/x $ pip freeze
attrs==19.1.0
jsonschema==3.0.1
pyrsistent==0.14.11
python-slugify==3.0.2
six==1.12.0
spidermon==1.9.0
text-unidecode==1.2
```

Let me dig more into this, there surely would be a reason why Spidermon doesn't install all the packages that are needed from the get-go. I have a gut feeling that I have read a issue on this exact topic while doing my research for the CLI. I will link back to this issue as soon as possible. Till then, I atleast know this was not a mistake as the [documentation](https://spidermon.readthedocs.io/en/latest/item-validation.html#with-schematics) clearly mentions to install `schematics` if you plan to use it.

**Comment by vipulgupta2048** [comment]
Found it, #89 and #88 have discussion threads where the same discussion rose on json-schema. I feel both @rennerocha and @victor-torres had good points to say. But, there is a limit to what the expression `Comes with Batteries Included` mean and in case of Spidermon, a line should be drawn when packages are considered. I recommend installing whichever package you require as per the feature you want to use as per the docs. We only take that tool out of a swiss army knife that we need for the time being, not all of them once.
 
Alongwith this, I have also found an easy fix to your issue. `Setup.py` file lists `schematics` as optional leading to it not being installed at `pip install spidermon`
 
For reference
https://github.com/scrapinghub/spidermon/blob/976257cec8747205cd720161fd4af17d76e60778/setup.py#L41

A simple PR would be fix that, if need be. I am wee bit new to the community, but happy to help. If this resolved your issue, do mark it closed. 
Thanks,
CC: @ejulio @raphapassini

**Comment by ejulio** [comment]
As it looks to me, it follows the discussions pointed by @vipulgupta2048.
Validation is not included by default in spidermon. If you need item validation, then `pip install spidermon[validation]` is the way to go.
The error is, probably, being raised, because the `ItemValidation` pipeline was enabled but the required dependencies weren't installed.
If this behavior persist when disabling the pipeline, then it should be a bug in the library.

**Comment by andrewbaxter** [comment]
I agree with all the points here - I think what I'd like to highlight is:

> the [documentation](https://spidermon.readthedocs.io/en/latest/item-validation.html#with-schematics) clearly mentions to install `schematics` if you plan to use it

In my case I do not plan to use it, and it's not documented that `schematics` is required if you want to use jsonschema.

> If you need item validation, then `pip install spidermon[validation]` is the way to go

This _sounds_ like the proper solution, but https://spidermon.readthedocs.io/en/latest/item-validation.html doesn't mention `spidermon[validation]` - I would assert that people who decide to add validation later are unlikely to go and re-read [the installation docs](https://spidermon.readthedocs.io/en/latest/installation.html).  And in my case I'm not sure I've ever read that page, I actually read [these installation instructions](https://github.com/scrapinghub/spidermon#install) which don't mention validation.

--

Since #88 and #89 came up again, I would add my vote for batteries included - this is the only package I've ever used that uses the package[opt] notation.  Perhaps it would be less confusing though if the validation stuff were broken off, along with dependencies, into a separate spidermon-validation package?  Then it would be clear that a separate package is required because you'd get an error doing `import spidermon_validation.whatever` rather than a less instructional error about schematics later.

**Comment by rennerocha** [comment]
There is a plan to refactor ItemValidationPipeline to remove this requirement. After that you will only be asked to install schematics if your are using it (the same for JSON Schema). For now, you really need to install it to be able to use spidermon.
