### ISSUE TITLE
Improve documentation regarding tokens for actions

### ISSUE THREAD

**Issue by vipulgupta2048** [scrapinghub/spidermon#141]
First Issue :hatching_chick: 

Actions for Spidermon can use a little more descriptive documentation regarding tokens, settings and key-value pairs essential for working of almost all actions and developers to implement the same in their spiders.  

I am currently working on adding more to the Slack actions.
Would love to have someone collaborate with me on the same. 
Will continue to update this issue with updates and more information.

**Comment by kishan3** [comment]
@Gallaecio Can this be closed as PR for this is closed?

**Comment by Gallaecio** [comment]
@vipulgupta2048 Thoughts?

**Comment by vipulgupta2048** [comment]
Thanks for pinging this issue back into action @kishan3 
I planned to work more on it, improving each section of the documentation related to actions. Till now, I have managed to add information to only Slack action. Feel free to open a new PR to improve more actions. Otherwise, closing it for now.
