### ISSUE TITLE
Spidermon Command Line Interface: Origins and Road-map 🐣

### ISSUE THREAD

**Issue by vipulgupta2048** [scrapinghub/spidermon#146]
Hello folks :hatching_chick:, 

![Hello](https://media.giphy.com/media/dzaUX7CAG0Ihi/giphy.gif)

I was thinking of creating this issue for a while now in reference to #74. This issue contains a brief summary of the plans, features, and build methods for the Spidermon CLI from @vipulgupta2048 (Hello!) prepared through great help from @ejulio @raphapassini @rennerocha @cathalgarvey @stav @manycoding 

The discussion will be continued in the next few comments. Thank you,

**Comment by vipulgupta2048** [comment]
For starters, here's the feature map. 
![24dd00d05ad811e9817163bfee143b7e map](https://user-images.githubusercontent.com/22801822/55861207-861edb00-5b93-11e9-8ec2-46df223dcf98.jpg)

[Click this link for a better, closer look.](https://atlas.mindmup.com/2019/04/b8c753505ad711e9904a63e5aaa82b2a/cli2048/index.html)

Navigating the feature map: 
**Red** - Root node, contains keyword which is “spidermon”    
**Blue** - Information about the map
**Black** - Keyword + [command]
**Grey** - Keyword + [command] + --options

I have added a complete timeline along with a fairly detailed build process as to how we can achieve this humongous task. There are several issues that need to be solved as well as docs that need to be written for the CLI's correct implementation. **Please do suggest any additions, subtractions and divisions that you would like to see in this initial feature list.** I would be more than happy to refactor the same.

**Comment by vipulgupta2048** [comment]
Regarding implementation, we have several great choices as well. 

Alternative ways to build CLI tools from I research:
- [Argparse](https://docs.python.org/3/library/argparse.html) (Used in Scrapy CLI, quite powerful magic behind parsing)  (Choose :+1:)
- [Click](https://click.palletsprojects.com/en/7.x/) (Decorator styled options makes code, cleaner, and easier to read)  (Choose :heart:)
- Docopt (Use docstrings to create options for the CLI) (Choose :tada: )

I feel this [blog](https://realpython.com/comparing-python-command-line-parsing-libraries-argparse-docopt-click/) by Dan Bader, would help make a clear distinction between the three choices. I like to go with Click. We can have a small poll for this matter. Please comment on this issue with the emoji of the alternative you like the most. Or just mark :eyes: if you read through the issue. I would really appreciate everyone's participation.

I am creating this issue to take an initiative and get the ball rolling for the CLI issue. Looking forward to contributing and having a great postive discussion with the community to build a good command line in the summer with all of your help and support.
Thanks,

**Comment by stav** [comment]
Nice work @vipulgupta2048  

_Click_ is easy to use because of the nice decorators but if you are going to implement sub-commands then I recommend using [Cliff](https://docs.openstack.org/cliff/latest/user/introduction.html)

    The cliff framework is meant to be used to create multi-level
    commands such as subversion and git, where the main program
    handles some basic argument parsing and then invokes a sub-command
    to do the work.

    Command Plugins: Cliff takes advantage of Python’s ability to load
    code dynamically to allow the sub-commands of a main program to be
    implemented, packaged, and distributed separately from the main
    program.


* https://blog.swdev.ed.ac.uk/2017/04/28/writing-python-command-line-tools-with-cliff

**Comment by rennerocha** [comment]
This issue is being developed by @leovictorsr during GSOC 2019 (Issue #74). This issue is duplicated.
