### ISSUE TITLE
Unclear jsonschema error about unknown fields

### ISSUE THREAD

**Issue by andrewbaxter** [scrapinghub/spidermon#175]
If you have `"additionalProperties": true` in your jsonschema and validation detects an unknown field you get this message in `_validation`:
```
'': ['Unexpected field']
```
If you have a lot of fields and mistyped one it can make it very difficult tracking down which field is wrong.

**Comment by rosheen33** [comment]
@rennerocha I have talked to @andrewbaxter and also tested it locally and seems like it is been resolved.
@andrewbaxter reported this right before 1.10.0 was released

![image](https://user-images.githubusercontent.com/7950673/59759067-bb892880-92a8-11e9-911a-0999980dc192.png)

**Comment by rosheen33** [comment]
@rennerocha Can you please close this issue ?
