### ISSUE TITLE
Add Documentation for EXPRESSION MONITOR

### ISSUE THREAD

**Issue by rosheen33** [scrapinghub/spidermon#179]
Fill in the missing docs for the following settings:

```
SPIDERMON_SPIDER_OPEN_EXPRESSION_MONITORS
SPIDERMON_SPIDER_CLOSE_EXPRESSION_MONITORS
SPIDERMON_EXPRESSIONS_MONITOR_CLASS
```

https://spidermon.readthedocs.io/en/latest/settings.html?highlight=SPIDERMON_SPIDER_OPEN_EXPRESSION_MONITORS

**Comment by raphapassini** [comment]
This PR will improve the documentation https://github.com/scrapinghub/spidermon/pull/178
