### ISSUE TITLE
Use other regions on AWS SES

### ISSUE THREAD

**Issue by thamenato** [scrapinghub/spidermon#189]
Hi, I currently ran into that problem and couldnt really solve it by simply adding the environment variable `AWS_DEFAULT_REGION` into something else than `us-east-1`. I made a local patch to use a different function from `boto.ses` which allows you to set the `region_name`.

I would like to know if I can send a pull request and how I can do it. 

Thanks

**Comment by vipulgupta2048** [comment]
Hi @thamenato, thanks for using Spidermon. Could you tell a little more about the exact problem you faced that would be helpful to debug this on our end? Regarding the PR, yes, you can send a PR. One of the maintainers can review and suggest changes to it. 

Guide to making a PR --> https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by thamenato** [comment]
@vipulgupta2048  Just sent it! https://github.com/scrapinghub/spidermon/pull/190

My problem was that my SES is configured on `us-west-2` and when the class SendSESEmail tries to send the email with the function `session.send_raw_email()` it raises the following exception:
```
boto.ses.exceptions.SESAddressNotVerifiedError: SESAddressNotVerifiedError: 400 Email address is not verified.
...
... Email address is not verified. The following identities failed the check in region US-EAST-1: ...
```
So I figured that the problem was that boto was ignoring (or not even using) my `DEFAULT_AWS_REGION` environment variable.

Once I changed the function and set the region it worked like a charm.

**Comment by rennerocha** [comment]
Hello @thamenato ,

I believe that you need to change [this method](https://github.com/scrapinghub/spidermon/blob/master/spidermon/contrib/actions/email/ses.py#L33) so the region can be set. This would be a great improvement in our SES e-mail action.

Feel free to send a PR so we can add this new option in our next Spidermon release.
