### ISSUE TITLE
Update list settings to use settings.getlist

### ISSUE THREAD

**Issue by ejulio** [scrapinghub/spidermon#210]
Some list-like settings, `SPIDERMON_EMAIL_TO` for example, [are loaded using `settings.get`](https://github.com/scrapinghub/spidermon/blob/master/spidermon/contrib/actions/email/__init__.py#L77). Then, they need to be [formatted properly](https://github.com/scrapinghub/spidermon/blob/master/spidermon/contrib/actions/email/__init__.py#L147). By updating to `getlist` the method is not required, as it is always a `list`, so we only need to join the value.

I suggest to start using [`settings.getlist`](https://github.com/scrapy/scrapy/blob/master/scrapy/settings/__init__.py#L167) as it is standard across scrapy and we can follow conventions for it.

**Comment by rennerocha** [comment]
Fixed in https://github.com/scrapinghub/spidermon/pull/238.
