### ISSUE TITLE
TravisCI build badge point only to master

### ISSUE THREAD

**Issue by BurnzZ** [scrapinghub/spidermon#217]
We upgraded to the latest version of spidermon last night and was encountering an issue in production.

While investigating the issue by browsing through the repo, I've noticed that the current build was failing. At first I thought the issue with our production use was discovered, but it turns out that the Travis CI build badge we're using in the `README.rst` doesn't point to just the master branch, but to any new branch.

This might be a bit misleading as the build badge should point to the `master` branch to indicate the health of the project overall, not whenever any branch is updated in the repo.

What do you think about only pointing it to `master`?

![image](https://user-images.githubusercontent.com/3449761/65484996-244cf600-ded3-11e9-9d12-b9167b0c8183.png)

**Comment by vipulgupta2048** [comment]
Hello @BurnzZ, thanks for opening an issue regarding this :hatching_chick: 
I feel the build badge should be pointing the build status of the master branch only. But, I am sure there might be a reason for this, if not we will fix it shortly. Thanks for bringing it to our notice.

**Comment by rennerocha** [comment]
Hello @BurnzZ , thanks for pointing that. It is really incorrect and we should show only master status, not other branches. Created a PR to fix this issue.
