### ISSUE TITLE
Update slackclient version

### ISSUE THREAD

**Issue by rennerocha** [scrapinghub/spidermon#251]
`SendSlackMessage` action don't work with the 2.x `slackclient` versions. To avoid breaking spidermon, we are locked with 1.x version.

There is a guide for migrating the library as it was completely rewritten (so it is backward incompatible):
https://github.com/slackapi/python-slackclient/wiki/Migrating-to-2.x

This was related to this issue:
https://github.com/scrapinghub/scrapinghub-stack-scrapy/issues/141

**Comment by andersonberg** [comment]
I will start working on this issue

**Comment by rennerocha** [comment]
Thanks @andersonberg ! Please let me know if you need some assistance.
