### ISSUE TITLE
feature: Built-in monitor for field coverage

### ISSUE THREAD

**Issue by rennerocha** [scrapinghub/spidermon#253]
In certain spiders we can accept that not all items returned contains a certain field, but we expect that at least certain amount of items returned contains this field. We can use `ValidationMonitorMixin` to create monitors that do this kind of validation. However this requires us to write code and updating the thresholds requires changes in the source code.

My idea is to create a new built-in monitor, configured by a new setting that defines all item coverage rules in a more straightforward way. When an user defines this setting and enable the monitor, we will be notified when the rules weren't satisfied.

Example of proposed setting:
We have `myproject.MyItem`, the spider returns 100 of this item and we have the following configuration:

```
SPIDERMON_FIELD_COVERAGE = {
    "myproject.MyItem": {
        "field_name_1": {
            # Minimum percent of items that needs to have this field
            "min_percent": 10,
        },
        "field_name_2": {
            # Minimum number of items that needs to have this field
            "min_items": 5,
        },
    }
}
```

The new monitor will fail if:
- We have more than 10% of the items missing `field_name_1`; or
- We have more than 5 items missing `field_name_2`.

Looking for comments over this proposal to improve it.

**Comment by simoess** [comment]
@rennerocha I think the proposed format will be a good format to standardize the way that the field coverage monitors are defined. A built-in monitor would be great. On most project's that I've worked on, the settings are usually defined this way:

SPIDER_NAME: {
    "field_name_1": min_percent,
    "field_name_2": min_percent,
    "composed_field_name": { # only one project that I've worked on had the option to define field coverage for composed fields
          "sub_field_name_1": min_percent
    }
}

It would be nice to be able to define monitors for  item coverage and field coverage in one place.

**Comment by Gallaecio** [comment]
For composed fields, in a project where I used to work we would use the “field path”, e.g. “composed_field_name/sub_field_name_1”.

Issues to consider:
- Fields containing `/` in their name would be a problem.
- Should relative values (percentages) be relative to the parent field or to the item count?
- List item count checks. If `field1` is a list, and you want to check totals of `len(field1)`.

**Comment by rennerocha** [comment]
`ValidationMonitorMixin` implementation requires that to be able to do this kind of validation, we need to set a field as required, even if it is not, or else we will not have the stats of the coverage. This new monitor should remove this need, so we can have fields that are not required (in the JSON schema for example), but we need some coverage.

**Comment by PTaylour** [comment]
I've seen a couple limitations with `ItemValidationPipeline` and `ValidationMonitorMixin` that seem relevant.


@rennerocha your format (with the ability to namespace fields within an item type) solves a particular problem I just ran in to.


### Different items where some field names are the same

Using `ItemValidationPipeline` with multiple items that share the same field names (eg `MyItem1.url`, `MyItem2.url`) will increment the same count in the stats.

```py
# is this 100 from MyItem1, MyItem2, or both?
spidermon/validation/fields/errors/missing_required_field/url': 100
```

<hr/>

### using `ValidationMonitorMixin` with multiple item types

There is a knock on limitation with `ValidationMonitorMixin` where percentages are measured against all items (total of `MyItem1` and `MyItem2`).

eg 

```py
# I can do this to check total number of url errors over all items divided by 
# the total number of items
self.check_fields_errors_percent(field_names=['urls'], allowed_percent=0.1)

# but what I really want to do is check the number of url errors for each item
# divided by the total number of items of that type
self.check_fields_errors_percent(field_names=['MyItem1/urls'], allowed_percent=0.25)
self.check_fields_errors_percent(field_names=['MyItem2/urls'], allowed_percent=0)
```
