### ISSUE TITLE
PyPI behind latest tagged release 

### ISSUE THREAD

**Issue by PTaylour** [scrapinghub/spidermon#256]
Hi! 👋

Looks like travis failed on the `v1.12.2` tagged commit and therefore didn't deploy to PyPI (https://travis-ci.org/github/scrapinghub/spidermon/builds/684233498).

PyPI is still stuck on `v1.12.0` (https://pypi.org/project/spidermon/)

![image](https://user-images.githubusercontent.com/3678476/83749736-18b5ef80-a65c-11ea-85ee-6b097f54e61e.png)

**Comment by rennerocha** [comment]
Fixed with release of Spidermon 1.13.0.
