### ISSUE TITLE
Recursive item logging is creating unnecessary noise

### ISSUE THREAD

**Issue by MartiONE** [scrapinghub/spidermon#281]
Hello everyone,

I've been implementing Spidermon for the project I am working in right now and I noticed that upon enabling `'SPIDERMON_ADD_FIELD_COVERAGE' : True` the logs were getting way out of hand. The reason behind is that we save data on placeholder `Item` fields as a dictionary and then that data is picked up by the recursive nature of the [stat logging system](https://github.com/scrapinghub/spidermon/blob/master/spidermon/contrib/scrapy/extensions.py#L150) which creates an entry for every single image, raw dictionary, or anything that is different.

To solve this I implemented a setting called `'SPIDERMON_IGNORE_LOG_FIELDS'` that can be set to either a `List` or a `Dict` eg:

`'SPIDERMON_IGNORE_LOG_FIELDS': {'DetailItem': ['raw_data', 'image_caption']}`
`'SPIDERMON_IGNORE_LOG_FIELDS': ['raw_data', 'image_caption']`

Being the first one more restrictive on which type of item this ignore filter is applied.

I am raising this question to see if you guys find interesting this addition and if so, I will create a PR porting the code I've created to be added here.

Let me know what do you think and/or any clarification,
Alejandro

**Comment by rennerocha** [comment]
Hello @MartiONE ,

After enabling `SPIDERMON_ADD_FIELD_COVERAGE` we increase the size of the stats of the spider, and if you have too many fields in your items (nested fields included), stats that are logged in the end of the spider execution will certainly increases in size. However, this is the desired behavior, as the main idea of adding these logs is to have full coverage information of all fields returned.

In my opinion, selectively counting fields just to avoid logs to be too long will increase the complexity of the extension with extra settings and more code, doesn't add much value to the majority of the users.

As the stats are logged by [Scrapy](https://github.com/scrapy/scrapy/blob/master/scrapy/statscollectors.py#L46) (and not Spidermon), I can see two ways to reduce the size of your logs:
- Disabling [SCRAPY_DUMP](https://docs.scrapy.org/en/latest/topics/settings.html?highlight=SCRAPY_DUMP#stats-dump) that remove the stats from the logs, but you will still have access to it on your monitors;
- Or if you want to have the stats logged and just want to get rid of some entries, create a custom [StatsCollector](https://github.com/scrapy/scrapy/blob/master/scrapy/statscollectors.py#L10], overriding [close_spider](https://github.com/scrapy/scrapy/blob/master/scrapy/statscollectors.py#L44) regarding what to log.
