### ISSUE TITLE
Doc building error

### ISSUE THREAD

**Issue by wRAR** [scrapinghub/spidermon#283]
`tox -e docs` outputs:

Warning, treated as error:
/home/travis/build/scrapinghub/spidermon/docs/source/actions.rst:5:duplicate label actions, other instance in /home/travis/build/scrapinghub/spidermon/docs/source/actions.rst

Note that this doesn't fail the PR checks, not sure if that's intended (maybe because the check runs several tox commands separated by semicolons and the shell eats the exit code).

**Comment by wRAR** [comment]
Yup, other files are affected too, as can be checked by removing `-W` from the build command.

**Comment by rennerocha** [comment]
Docs building errors fixed with https://github.com/scrapinghub/spidermon/pull/290 and https://github.com/scrapinghub/spidermon/pull/292.
