### ISSUE TITLE
Allow pass extra optional arguments to Slack API

### ISSUE THREAD

**Issue by rennerocha** [scrapinghub/spidermon#293]
When sending a [Slack message](https://github.com/scrapinghub/spidermon/blob/master/spidermon/contrib/actions/slack/__init__.py#L111) we don't have an easy way to provide extra arguments to [postMessage](https://api.slack.com/methods/chat.postMessage) method (`mrkdwn` or `thread_ts` for example). It would be good to be able to provide extra arguments.

My use case is that I have an already created thread on  a monitoring Slack channel and I want that Spidermon notifications goes to a specific thread instead of going as a new message on the main channel.

**Comment by andersonberg** [comment]
I can handle this if anyone is assigned

**Comment by rennerocha** [comment]
> I can handle this if anyone is assigned

It would be great!

**Comment by rennerocha** [comment]
This issue is related to https://github.com/scrapinghub/spidermon/issues/313 . We need to allow these extra arguments using the new Slack library.
