### ISSUE TITLE
Built-in monitor for max number of failed responses allowed

### ISSUE THREAD

**Issue by rennerocha** [scrapinghub/spidermon#302]
Validate maximum amount of `downloader/response_status_count/XXX` for failed responses (4xx or 5xx responses) in general. Maybe have two configurations, one for client errors (4xx) and other for server errors (5xx).

If we want a more granular control (for example, set a threshold only for 503 errors), we already have [UnwantedHTTPCodesMonitor](https://spidermon.readthedocs.io/en/latest/monitors.html#spidermon.contrib.scrapy.monitors.UnwantedHTTPCodesMonitor)

**Comment by arslan-shafiq-zyte** [comment]
Hi @rennerocha 
I am looking into it. Thank you.

**Comment by arslan-shafiq-zyte** [comment]
Hi @rennerocha 
I am looking into it. Thank you.
