### ISSUE TITLE
Replace slackclient with slack-sdk for Slack action

### ISSUE THREAD

**Issue by rennerocha** [scrapinghub/spidermon#313]
[slackclient](https://pypi.org/project/slackclient/) is under [maintenance](https://slack.dev/python-slackclient/) mode, being replaced by [slack-sdk](https://pypi.org/project/slack-sdk/) library. Considering that this is a Spidermon third-party integration that is used by so many projects and that Slack can change their APIs without us even noticing it, it would be good if we keep our library as much updated as possible with theirs.

**Comment by ankitjavalkar** [comment]
I'd like to work on this issue.

I see the slack documentation provides a few suggestions for migrations [here](https://slack.dev/python-slack-sdk/v3-migration/index.html#from-slackclient-2-x), will these suggested changes be sufficient?

**Comment by rennerocha** [comment]
> I'll be working on this issue.
> 
> I see the slack documentation provides a few suggestions for migrations [here](https://slack.dev/python-slack-sdk/v3-migration/index.html#from-slackclient-2-x), will these suggested changes be sufficient?

Apparently this change is simple like that.

**Comment by rennerocha** [comment]
Fixed by https://github.com/scrapinghub/spidermon/pull/338
