### ISSUE TITLE
Remove use of private module from jsonschema

### ISSUE THREAD

**Issue by rennerocha** [scrapinghub/spidermon#315]
`jsonschema` latest version removed `jsonschema.compat` module. [According to its author]([https://github.com/Julian/jsonschema/issues/843#issuecomment-931247200), this module was intended to be private and not used by external users.

We are using this module in some JSON Schema [custom validators](https://github.com/scrapinghub/spidermon/blob/master/spidermon/contrib/validation/jsonschema/formats.py#L2), and I received reports from users that had problems with it.

Considering that `jsonschema.compat` was created just for compatibility with older Python version, and that we don't have this requirement anymore, we should update there to avoid this issue when using the newest version of the library.

**Comment by aaneto** [comment]
Hi @rennerocha!

I have started a local fork of the repository and would like to work on this issue :)

**Comment by aaneto** [comment]
Hi,

I'm closing this as this issue was fixed in #364 :)
