### ISSUE TITLE
ModuleNotFoundError: No module named 'spidermon.contrib.actions.discord'

### ISSUE THREAD

**Issue by bishalnepali** [scrapinghub/spidermon#350]
Hi there I am trying to use the discord notification but not able to import the file

`from spidermon.contrib.actions.discord.notifiers import SendDiscordMessageSpiderFinished`
 
I am using the latest version
<img width="571" alt="image" src="https://user-images.githubusercontent.com/66122349/176789162-f478ec5f-47f0-478a-8f3c-22b4a9536332.png">

Thanks!

**Comment by rennerocha** [comment]
Hello @bishalnepali ,

Discord integration is not released yet. It is already in `master` branch (the `latest` [documentation](https://spidermon.readthedocs.io/en/latest/actions/index.html)), but not available in the current [stable version](https://spidermon.readthedocs.io/en/1.16.2/actions/index.html) (1.16.2). If you want to use it right now, you will need to install the version in the `master` branch.

We expect to have a new release of Spidermon in the next weeks, so Discord integration will be available in the stable version soon.

**Comment by Laerte** [comment]
> Hello @bishalnepali ,
> 
> Discord integration is not released yet. It is already in `master` branch (the `latest` [documentation](https://spidermon.readthedocs.io/en/latest/actions/index.html)), but not available in the current [stable version](https://spidermon.readthedocs.io/en/1.16.2/actions/index.html) (1.16.2). If you want to use it right now, you will need to install the version in the `master` branch.
> 
> We expect to have a new release of Spidermon in the next weeks, so Discord integration will be available in the stable version soon.

You can install using:

```
pip install -e git+ssh://git@github.com/scrapinghub/spidermon.git@master#egg='spidermon[monitoring]'
```

**Comment by bishalnepali** [comment]
Many thanks! @rennerocha @Laerte 👍 .
