### ISSUE TITLE
bug: Docs build in Python 3.10 throws error

### ISSUE THREAD

**Issue by curita** [scrapinghub/spidermon#354]
At the moment the Python 3.10 docs build throws an error in `master`.

**Logs:**
```
Warning, treated as an error:
/home/runner/work/spidermon/spidermon/docs/source/actions/email-action.rst:67:broken link: https://docs.scrapy.org/en/latest/topics/settings.html#std:setting-AWS_ACCESS_KEY_ID (Anchor 'std:setting-AWS_ACCESS_KEY_ID' not found)
ERROR: InvocationError for command /home/runner/work/spidermon/spidermon/.tox/docs/bin/sphinx-build -W -b linkcheck source/ /home/runner/work/spidermon/spidermon/.tox/docs/tmp/linkcheck (exited with code 2)
```

It could be worth it to pin dependencies (sphinx?) to avoid builds from failing after library updates.

**Comment by wRAR** [comment]
Looks like the quoted link doesn't exist, the new one is https://docs.scrapy.org/en/latest/topics/settings.html#aws-access-key-id so I guess the code should be updated.
