### ISSUE TITLE
No dep on slack-sdk

### ISSUE THREAD

**Issue by wRAR** [scrapinghub/spidermon#363]
In #338 slackclient was replaced by slack-sdk in setup.py only in `test_requirements` but not in `extras_require`, so installing `spidermon[monitoring]` doesn't install it and the Slack action no longer works.

**Comment by rennerocha** [comment]
As a fallback, installing `slack-sdk` manually using `pip install slack-sdk` and/or adding `slack-sdk` in the requirements would be enough.

Perhaps `monitoring` section should be updated/removed in future. Using `pip install spidermon[slack]` (when we need Slack), `pip install spidermon[amazon]` (when using Amazon stuff) or `pip install spidermon[jsonschema]` when using JSON Schema makes more sense to me and avoid us to install libraries that won't be used and keep the libraries installed more explicit.
