### ISSUE TITLE
Error when using custom job tags action class

### ISSUE THREAD

**Issue by vu3jej** [scrapinghub/spidermon#403]
I am trying to add tags using custom action classes by following the example here
https://spidermon.readthedocs.io/en/latest/actions/job-tags-action.html#spidermon-job-tags-to-remove

I am getting the following error on scrapy:2.9 stack on Scrapy Cloud

```
[quotes] [Spidermon] Less

======================================================================
ERROR: AddJobTagsPassed
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/spidermon/core/[actions.py](http://actions.py/)", line 39, in run
    [self.run](http://self.run/)_action()
  File "/usr/local/lib/python3.10/site-packages/spidermon/contrib/actions/jobs/[tags.py](http://tags.py/)", line 26, in run_action
    self.process_tags(job_metadata)
  File "/usr/local/lib/python3.10/site-packages/spidermon/contrib/actions/jobs/[tags.py](http://tags.py/)", line 38, in process_tags
    if tag not in job_metadata["tags"]:
TypeError: 'JobMeta' object is not subscriptable
```

Spidermon version:
```
spidermon==1.18.0
```

**Comment by VMRuiz** [comment]
These actions uses the [JobMeta](https://python-scrapinghub.readthedocs.io/en/latest/client/apidocs.html#scrapinghub.client.jobs.JobMeta) class from Python-Scrapinghub package to update the tag information from jobs run in Scrapy Cloud.

At some point its interface must have been changed to onlly allow using  `get` and `set` methods to read and write job's metadata. I will release a fix for this.
