### ISSUE TITLE
Change format of content of _validation field

### ISSUE THREAD

**Issue by rennerocha** [scrapinghub/spidermon#425]
If a validation error is found and [SPIDERMON_VALIDATION_ADD_ERRORS_TO_ITEMS](https://spidermon.readthedocs.io/en/1.20.0/item-validation.html#spidermon-validation-add-errors-to-items) setting is `True`, we populate the `_validation` field with the errors.

The content of this field is the string representation of a Python defaultdict such as:
` '_validation': defaultdict(<class 'list'>, {'author_url': ['Invalid URL']})`

To make this field valid as JSON, we should have it as a list of objects such as:
` '_validation': [ {'author_url': ['Invalid URL'] }]`

This change will improve the data returned, making it possible to be read as a JSON.

**Comment by rochamatcomp** [comment]
Can I take this issue? I have created this pull request #431.

**Comment by Laerte** [comment]
Can we close this issue since was implemented? cc: @Gallaecio @VMRuiz
