### ISSUE TITLE
Make basic monitors part of the spidermon.

### ISSUE THREAD

**Issue by muzaffaryousaf** [scrapinghub/spidermon#72]
We have to add basic monitors for almost all the projects and the goal is to make such monitors part of the tool/spidermon itself and upon enabling them, the tool should send notifications automatically when integrated with a project. 

- [ ] Basic monitors inside the spidermon.
- [ ] One should be able to add customized monitors in a project in addition to these basic monitors.
- [ ] On should be able to disable these monitors and add their own monitors.

**Comment by muzaffaryousaf** [comment]
@rennerocha @raphapassini FYI, I've added list of basic monitors and expectations here.

**Comment by muzaffaryousaf** [comment]
Hi @raphapassini Would you be able to take this on ? Thanks.

**Comment by muzaffaryousaf** [comment]
@raphapassini I'm assigning this to you as we spoke yesterday. Please let me know otherwise. Thanks.

**Comment by raphapassini** [comment]
I'll start the implementation today, you should here from me soon :)

**Comment by raphapassini** [comment]
The PR is finished and waiting for review!

**Comment by rennerocha** [comment]
Merged
