### ISSUE TITLE
Infers validator class based on given JSON Schema

### ISSUE THREAD

**Issue by rennerocha** [scrapinghub/spidermon#76]
Actually it is using draft-4 version:
https://github.com/scrapinghub/spidermon/blob/master/spidermon/contrib/validation/jsonschema/validator.py#L27

**Comment by rennerocha** [comment]
The actual stable release of `jsonschema` (used by spidermon to validate against the schemas) supports only draft-3 and draft-4:
https://python-jsonschema.readthedocs.io/en/stable/validate/#versioned-validators

Only in the latest version (3.0.0a4.dev71+g6f10ce6 not released yet) the support for draft-6 and draft-7 is included:
https://python-jsonschema.readthedocs.io/en/latest/validate/#versioned-validators

We could:

1. wait for the release of version 3.0.0 (the alpha versions seems very active, so maybe it won't take long)
1. use a different library that supports all drafts

At this moment, I'd rather prefer to keep this library and wait for a release, but if good library alternatives exists we could verify if the change will be suitable.

**Comment by manycoding** [comment]
@rennerocha  What stops you from using jsonschema master branch? We have been using several months, I haven't encountered any issues and I think considering the usual needs for schema validation it should be just fine.

**Comment by rennerocha** [comment]
For an official release, I'd prefer to rely on a stable version of any other library that we depend on. After reading the code of jsonschema, I believe it will be possible to change it in a way that will work correctly with the master branch and the stable version.

Actually we have the validator defined hard-coded, but it is possible to get it passing the draft number or using the newest as default, so if you have the old version of jsonschema installed it will be draft-4, but if you have in your environment the latest version, it will be draft-7.

I will try to work on this next week.

**Comment by manycoding** [comment]
Yep you can infer the draft from `jsonshcema.validators.validator_for(schema)`
One thing - by default jsonschema returns the latest draft if there's nothing to infer upon, but it will change so you will get an error instead.

**Comment by rennerocha** [comment]
@manycoding I updated the validator, so it will be a task for `jsonschema` to determine the best validator for the provided schema. I tested with jsonschema 3.0.0b3 and apparently it is working correctly. Could you please take a look at the PR and test the branch?
