### ISSUE TITLE
Black to handle pep8 and all code formating

### ISSUE THREAD

**Issue by manycoding** [scrapinghub/spidermon#91]
I have noticed here and there formatting issues in prs, I suggest looking at https://github.com/ambv/black.

The setup is simple - add few lines of settings to `tox.ini`, autoformat the code with `black ./`, and add a line to CI to check everything is ok.

The main benefit - it allows to focus on code, it brings consistency, integrations with IDEs are good.
The main cons for me - it's a pre-release package, and why it's very stable `-pre` is a special case.

I am ready to help.

**Comment by manycoding** [comment]
@rennerocha @raphapassini

**Comment by rennerocha** [comment]
I like the idea of using something like black to format our code. I have been using it in some projects and it removes friction between developers coding styles.
